Prevent errors on delete for placeable mixers.
Error: Running LUA method 'mouseEvent'.
.../FS22_manureSystem/src/placeables/specializations/ManureSystemPlaceableMixers.lua:178: bad argument #1 to 'ipairs' (table expected, got nil))

I can not reproduce this myself, but it has been reported from several people. This change should prevent the error.